spring:
  datasource:
    url: jdbc:mysql://auction-service-mysql:3306/auctions?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: auction-kafka:29092

logging:
  level:
    com.ch.auction: DEBUG
