spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_db
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.ch.auction: DEBUG
