spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/chat_db
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: auction-kafka:29092

logging:
  level:
    com.ch.auction: DEBUG
