spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payments?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.ch.auction: DEBUG
