spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  kafka:
    bootstrap-servers: localhost:9092

aws:
  s3:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: password
    bucket: auction-bucket
    region: us-east-1

logging:
  level:
    com.ch.auction: DEBUG
