spring:
  datasource:
    url: jdbc:mysql://user-service-mysql:3306/users?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: auction-kafka:29092

jwt:
  secret: c2VjcmV0LWtleS1mb3ItYXVjdGlvbi1wcm9qZWN0LXRlc3QtMTIzNDU2Nzg5MA==

logging:
  level:
    com.ch.auction: DEBUG
