apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
  type: ClusterIP # 서비스들이 'kafka:9092'로 접근할 수 있도록 ClusterIP 서비스로 변경
